### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by galfridus** [amorphous1/hf4_to_ebook#1]
When running on Core PDF from 2021-10-09:

  File "C:\Users\geoff\Documents\GitHub\hf4_to_ebook\main.py", line 125, in <module>
    out.write(extract_page(left, 2 * pagenum + 2 + 100 * docnum))
  File "C:\Users\geoff\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2646' in position 2038: character maps to <undefined>

This looks to be the Neptune symbol on page 4.

Python 3.10.2, Windows (which maybe has a different default encoding?).

**Comment by galfridus** [comment]
Changing the output line to:

    with open("hf4.md", "w", encoding="utf-8") as out:  # `pandoc hf4.md -o hf4.epub metadata.txt --toc-depth=2` to generate

fixes this and produces output.

**Comment by amorphous1** [comment]
Good point, I never tested this under Windows. Explicitly specifying the encoding does not change anything in Linux land and is better anyway, so I've updated the script accordingly.
